<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>wojtryb Scripts</text>

        <Action name="pickSubwindow">
        <icon></icon>
        <text>pickSubwindow</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>ctrl+alt+m</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
        
        <Action name="splitScreen">
        <icon></icon>
        <text>splitScreen</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>ctrl+alt+n</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>

    </Actions>
</ActionCollection>
